<?php

namespace DoctrineProxies\__CG__\User\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserEntity extends \User\Domain\Entities\UserEntity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'affiliate' => [parent::class, 'affiliate', null, 16],
        "\0".parent::class."\0".'apiKey' => [parent::class, 'apiKey', null, 16],
        "\0".parent::class."\0".'cityName' => [parent::class, 'cityName', null, 16],
        "\0".parent::class."\0".'countryCode' => [parent::class, 'countryCode', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'currentWorkspace' => [parent::class, 'currentWorkspace', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'emailVerificationToken' => [parent::class, 'emailVerificationToken', null, 16],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'ip' => [parent::class, 'ip', null, 16],
        "\0".parent::class."\0".'isEmailVerified' => [parent::class, 'isEmailVerified', null, 16],
        "\0".parent::class."\0".'language' => [parent::class, 'language', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'lastSeenAt' => [parent::class, 'lastSeenAt', null, 16],
        "\0".parent::class."\0".'ownedWorkspaces' => [parent::class, 'ownedWorkspaces', null, 16],
        "\0".parent::class."\0".'passwordHash' => [parent::class, 'passwordHash', null, 16],
        "\0".parent::class."\0".'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        "\0".parent::class."\0".'preferences' => [parent::class, 'preferences', null, 16],
        "\0".parent::class."\0".'recoveryToken' => [parent::class, 'recoveryToken', null, 16],
        "\0".parent::class."\0".'referredBy' => [parent::class, 'referredBy', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'workspaceCap' => [parent::class, 'workspaceCap', null, 16],
        "\0".parent::class."\0".'workspaces' => [parent::class, 'workspaces', null, 16],
        'affiliate' => [parent::class, 'affiliate', null, 16],
        'apiKey' => [parent::class, 'apiKey', null, 16],
        'cityName' => [parent::class, 'cityName', null, 16],
        'countryCode' => [parent::class, 'countryCode', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'currentWorkspace' => [parent::class, 'currentWorkspace', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'emailVerificationToken' => [parent::class, 'emailVerificationToken', null, 16],
        'firstName' => [parent::class, 'firstName', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'ip' => [parent::class, 'ip', null, 16],
        'isEmailVerified' => [parent::class, 'isEmailVerified', null, 16],
        'language' => [parent::class, 'language', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'lastSeenAt' => [parent::class, 'lastSeenAt', null, 16],
        'ownedWorkspaces' => [parent::class, 'ownedWorkspaces', null, 16],
        'passwordHash' => [parent::class, 'passwordHash', null, 16],
        'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        'preferences' => [parent::class, 'preferences', null, 16],
        'recoveryToken' => [parent::class, 'recoveryToken', null, 16],
        'referredBy' => [parent::class, 'referredBy', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'workspaceCap' => [parent::class, 'workspaceCap', null, 16],
        'workspaces' => [parent::class, 'workspaces', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
