<?php

namespace DoctrineProxies\__CG__\Workspace\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WorkspaceEntity extends \Workspace\Domain\Entities\WorkspaceEntity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'address' => [parent::class, 'address', null, 8],
        "\0".'*'."\0".'creditCount' => [parent::class, 'creditCount', null, 8],
        "\0".parent::class."\0".'anthropicApiKey' => [parent::class, 'anthropicApiKey', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'creditsAdjustedAt' => [parent::class, 'creditsAdjustedAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'invitations' => [parent::class, 'invitations', null, 16],
        "\0".parent::class."\0".'isTrialed' => [parent::class, 'isTrialed', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'openaiApiKey' => [parent::class, 'openaiApiKey', null, 16],
        "\0".parent::class."\0".'owner' => [parent::class, 'owner', null, 16],
        "\0".parent::class."\0".'subscription' => [parent::class, 'subscription', null, 16],
        "\0".parent::class."\0".'subscriptions' => [parent::class, 'subscriptions', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null, 16],
        "\0".parent::class."\0".'voices' => [parent::class, 'voices', null, 16],
        'address' => [parent::class, 'address', null, 8],
        'anthropicApiKey' => [parent::class, 'anthropicApiKey', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'creditCount' => [parent::class, 'creditCount', null, 8],
        'creditsAdjustedAt' => [parent::class, 'creditsAdjustedAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'invitations' => [parent::class, 'invitations', null, 16],
        'isTrialed' => [parent::class, 'isTrialed', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'openaiApiKey' => [parent::class, 'openaiApiKey', null, 16],
        'owner' => [parent::class, 'owner', null, 16],
        'subscription' => [parent::class, 'subscription', null, 16],
        'subscriptions' => [parent::class, 'subscriptions', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'users' => [parent::class, 'users', null, 16],
        'voices' => [parent::class, 'voices', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
