<?php

namespace DoctrineProxies\__CG__\Billing\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SubscriptionEntity extends \Billing\Domain\Entities\SubscriptionEntity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cancelAt' => [parent::class, 'cancelAt', null, 16],
        "\0".parent::class."\0".'canceledAt' => [parent::class, 'canceledAt', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'endedAt' => [parent::class, 'endedAt', null, 16],
        "\0".parent::class."\0".'externalId' => [parent::class, 'externalId', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'order' => [parent::class, 'order', null, 16],
        "\0".parent::class."\0".'paymentGateway' => [parent::class, 'paymentGateway', null, 16],
        "\0".parent::class."\0".'plan' => [parent::class, 'plan', null, 16],
        "\0".parent::class."\0".'renewAt' => [parent::class, 'renewAt', null, 16],
        "\0".parent::class."\0".'trialPeriodDays' => [parent::class, 'trialPeriodDays', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'usageCount' => [parent::class, 'usageCount', null, 16],
        "\0".parent::class."\0".'workspace' => [parent::class, 'workspace', null, 16],
        'cancelAt' => [parent::class, 'cancelAt', null, 16],
        'canceledAt' => [parent::class, 'canceledAt', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'endedAt' => [parent::class, 'endedAt', null, 16],
        'externalId' => [parent::class, 'externalId', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'order' => [parent::class, 'order', null, 16],
        'paymentGateway' => [parent::class, 'paymentGateway', null, 16],
        'plan' => [parent::class, 'plan', null, 16],
        'renewAt' => [parent::class, 'renewAt', null, 16],
        'trialPeriodDays' => [parent::class, 'trialPeriodDays', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'usageCount' => [parent::class, 'usageCount', null, 16],
        'workspace' => [parent::class, 'workspace', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
