<?php

namespace DoctrineProxies\__CG__\Billing\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PlanSnapshotEntity extends \Billing\Domain\Entities\PlanSnapshotEntity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'billingCycle' => [parent::class, 'billingCycle', null, 8],
        "\0".'*'."\0".'config' => [parent::class, 'config', null, 8],
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null, 8],
        "\0".'*'."\0".'creditCount' => [parent::class, 'creditCount', null, 8],
        "\0".'*'."\0".'description' => [parent::class, 'description', null, 8],
        "\0".'*'."\0".'featureList' => [parent::class, 'featureList', null, 8],
        "\0".'*'."\0".'icon' => [parent::class, 'icon', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'memberCap' => [parent::class, 'memberCap', null, 8],
        "\0".'*'."\0".'price' => [parent::class, 'price', null, 8],
        "\0".'*'."\0".'title' => [parent::class, 'title', null, 8],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null, 8],
        "\0".parent::class."\0".'plan' => [parent::class, 'plan', null, 16],
        'billingCycle' => [parent::class, 'billingCycle', null, 8],
        'config' => [parent::class, 'config', null, 8],
        'createdAt' => [parent::class, 'createdAt', null, 8],
        'creditCount' => [parent::class, 'creditCount', null, 8],
        'description' => [parent::class, 'description', null, 8],
        'featureList' => [parent::class, 'featureList', null, 8],
        'icon' => [parent::class, 'icon', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'memberCap' => [parent::class, 'memberCap', null, 8],
        'plan' => [parent::class, 'plan', null, 16],
        'price' => [parent::class, 'price', null, 8],
        'title' => [parent::class, 'title', null, 8],
        'updatedAt' => [parent::class, 'updatedAt', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
